# Auto Release contract case: 30-project-profiles.ps1
$nodeRoot = New-TestDirectory "node"
try {
  Write-TestUtf8 (Join-Path $nodeRoot "package.json") @'
{
  "name": "node-fixture",
  "version": "1.2.3",
  "scripts": {
    "test": "node --test",
    "build": "node build.js"
  }
}
'@
  Write-TestUtf8 (Join-Path $nodeRoot "package-lock.json") @'
{
  "name": "node-fixture",
  "version": "1.2.3",
  "lockfileVersion": 3,
  "packages": {
    "": {
      "name": "node-fixture",
      "version": "1.2.3"
    }
  }
}
'@
  $nodeDetection = (& $setupScript -Mode Detect -RepositoryRoot $nodeRoot) | ConvertFrom-Json
  Assert-Equal $nodeDetection.projectType "node" "Node fixture was not detected"
  Assert-Equal $nodeDetection.packageManager "npm" "Node package manager was not detected"
  if (Test-Path -LiteralPath (Join-Path $nodeRoot ".codex-release.json")) {
    throw "Detect mode wrote a release config"
  }
  & $setupScript -Mode Generate -RepositoryRoot $nodeRoot
  & $setupScript -Mode Validate -RepositoryRoot $nodeRoot
  $nodeConfigPath = Join-Path $nodeRoot ".codex-release.json"
  $nodeWorkflowPath = Join-Path $nodeRoot ".github\workflows\release.yml"
  & git -C $nodeRoot check-ignore -q --no-index -- .codex-release.json
  if ($LASTEXITCODE -ne 0) { throw "Node generation did not ignore the local config" }
  $nodeConfig = Get-Content -Raw -Encoding UTF8 $nodeConfigPath | ConvertFrom-Json
  Assert-Equal $nodeConfig.schemaVersion 2 "Node config does not use schema v2"
  Assert-Equal $nodeConfig.commit.policy "conventional" "Node config does not require Conventional Commits"
  Assert-Equal $nodeConfig.commit.fallback "conventional" "Node config has the wrong compatibility fallback"
  Assert-Equal $nodeConfig.automation.template "node-v1" "Node config uses the wrong template"
  Assert-Equal $nodeConfig.prepare.localOutputDirectory "output" "Node config does not use the unified local output directory"
  Assert-Equal @($nodeConfig.prepare.bootstrapCommands).Count 1 "Node dependency installation was not separated from build commands"
  Assert-Match ([string]$nodeConfig.prepare.bootstrapCommands[0].command) 'npm ci' "Node bootstrap does not use the detected lock file"
  Assert-Equal ([string]$nodeConfig.prepare.bootstrapRequiredPaths[0]) "node_modules" "Node bootstrap cache does not verify installed dependencies"
  Assert-Equal (@($nodeConfig.prepare.localCommands).Count) (@($nodeConfig.prepare.commands).Count) "Node local command set does not preserve build checks"
  Assert-Equal @($nodeConfig.version.updates).Count 3 "Node config did not constrain all root version entries"
  $nodeConfigHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $nodeConfigPath).Hash
  $nodeWorkflowHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $nodeWorkflowPath).Hash
  $nodeIgnoreHash = (Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $nodeRoot ".gitignore")).Hash
  & $setupScript -Mode Generate -RepositoryRoot $nodeRoot
  Assert-Equal (Get-FileHash -Algorithm SHA256 -LiteralPath $nodeConfigPath).Hash $nodeConfigHash "Node config generation is not idempotent"
  Assert-Equal (Get-FileHash -Algorithm SHA256 -LiteralPath $nodeWorkflowPath).Hash $nodeWorkflowHash "Node workflow generation is not idempotent"
  Assert-Equal (Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $nodeRoot ".gitignore")).Hash $nodeIgnoreHash "Node config ignore generation is not idempotent"

  $legacyConfig = Get-Content -Raw -Encoding UTF8 $nodeConfigPath | ConvertFrom-Json
  $legacyConfig.automation.generator = "project-release-automator"
  Write-TestUtf8 $nodeConfigPath (($legacyConfig | ConvertTo-Json -Depth 20) + "`n")
  $legacyWorkflow = [IO.File]::ReadAllText($nodeWorkflowPath).Replace(
    "# Generated by Auto Release",
    "# Generated by Project Release Automator"
  )
  Write-TestUtf8 $nodeWorkflowPath $legacyWorkflow
  & $setupScript -Mode Validate -RepositoryRoot $nodeRoot
  & $setupScript -Mode Generate -RepositoryRoot $nodeRoot
  $upgradedConfig = Get-Content -Raw -Encoding UTF8 $nodeConfigPath | ConvertFrom-Json
  Assert-Equal $upgradedConfig.automation.generator "auto-release" "Legacy config was not upgraded"
  Assert-Match (Get-Content -Raw -Encoding UTF8 $nodeWorkflowPath) '^# Generated by Auto Release' "Legacy workflow was not upgraded"
}
finally {
  Remove-TestDirectory $nodeRoot
}
$tauriRoot = New-TestDirectory "tauri"
try {
  Write-TestUtf8 (Join-Path $tauriRoot "src-tauri\tauri.conf.json") @'
{
  "productName": "Tauri Fixture",
  "version": "2.3.4",
  "identifier": "invalid.example.fixture"
}
'@
  Write-TestUtf8 (Join-Path $tauriRoot "src-tauri\Cargo.toml") @'
[package]
name = "tauri-fixture"
version = "2.3.4"
edition = "2021"
'@
  Write-TestUtf8 (Join-Path $tauriRoot "src-tauri\Cargo.lock") @'
version = 4

[[package]]
name = "tauri-fixture"
version = "2.3.4"
'@
  Write-TestUtf8 (Join-Path $tauriRoot "package.json") @'
{
  "name": "tauri-fixture",
  "version": "2.3.4",
  "scripts": {
    "tauri": "tauri",
    "test": "vitest"
  }
}
'@
  Write-TestUtf8 (Join-Path $tauriRoot "pnpm-lock.yaml") "lockfileVersion: '9.0'`n"
  $tauriDetection = (& $setupScript -Mode Detect -RepositoryRoot $tauriRoot) | ConvertFrom-Json
  Assert-Equal $tauriDetection.projectType "tauri" "Tauri fixture was not detected with highest priority"
  Assert-Equal $tauriDetection.packageManager "pnpm" "Tauri package manager was not detected"
  & $setupScript -Mode Generate -RepositoryRoot $tauriRoot
  & $setupScript -Mode Validate -RepositoryRoot $tauriRoot
  $tauriConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $tauriRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $tauriConfig.automation.template "tauri-v1" "Tauri config uses the wrong template"
  Assert-Equal @($tauriConfig.publish.release.requiredAssets).Count 6 "Tauri config does not validate all platform bundles"
  Assert-Match ([string]$tauriConfig.prepare.localCommands[-1].command) 'no-bundle' "Tauri local build still creates full installers"
  if ([string]$tauriConfig.prepare.commands[-1].command -match 'no-bundle') { throw "Tauri formal build incorrectly disables installer bundles" }
  $tauriWorkflow = Get-Content -Raw -Encoding UTF8 (Join-Path $tauriRoot ".github\workflows\release.yml")
  Assert-Match $tauriWorkflow 'windows-11-arm' "Tauri workflow is missing Windows ARM64"
  Assert-Match $tauriWorkflow 'x86_64-apple-darwin' "Tauri workflow is missing macOS Intel"
  Assert-Match $tauriWorkflow 'aarch64-apple-darwin' "Tauri workflow is missing macOS Apple Silicon"
  Assert-Match $tauriWorkflow 'x86_64-unknown-linux-gnu' "Tauri workflow is missing Linux"
}
finally {
  Remove-TestDirectory $tauriRoot
}

$goRoot = New-TestDirectory "go"
try {
  Write-TestUtf8 (Join-Path $goRoot "go.mod") "module example.invalid/team/go-fixture`n`ngo 1.24`n"
  Write-TestUtf8 (Join-Path $goRoot "cmd\go-fixture\main.go") "package main`n`nfunc main() {}`n"
  $goDetection = (& $setupScript -Mode Detect -RepositoryRoot $goRoot) | ConvertFrom-Json
  Assert-Equal $goDetection.projectType "go" "Go fixture was not detected"
  Assert-Equal $goDetection.buildPath "./cmd/go-fixture" "Go command build path was not detected"
  & $setupScript -Mode Generate -RepositoryRoot $goRoot
  & $setupScript -Mode Validate -RepositoryRoot $goRoot
  Assert-Equal ([IO.File]::ReadAllText((Join-Path $goRoot "VERSION")).Trim()) "0.1.0" "Go VERSION default is wrong"
  $goConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $goRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $goConfig.automation.template "go-v1" "Go config uses the wrong template"
  Assert-Equal @($goConfig.publish.release.requiredAssets).Count 6 "Go config does not validate six release assets"
}
finally {
  Remove-TestDirectory $goRoot
}

$pythonRoot = New-TestDirectory "python"
try {
  Write-TestUtf8 (Join-Path $pythonRoot "pyproject.toml") @'
[project]
name = "python-fixture"
version = "1.2.3"
requires-python = ">=3.10"
'@
  New-Item -ItemType Directory -Path (Join-Path $pythonRoot "tests") | Out-Null
  $pythonDetection = (& $setupScript -Mode Detect -RepositoryRoot $pythonRoot) | ConvertFrom-Json
  Assert-Equal $pythonDetection.projectType "python" "Python fixture was not detected"
  Assert-Equal $pythonDetection.packageManager "pip" "Python package manager fallback is wrong"
  & $setupScript -Mode Generate -RepositoryRoot $pythonRoot
  & $setupScript -Mode Validate -RepositoryRoot $pythonRoot
  $pythonConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $pythonRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $pythonConfig.automation.template "python-v1" "Python config uses the wrong template"
  Assert-Equal @($pythonConfig.publish.release.requiredAssets).Count 2 "Python config does not validate wheel and sdist"
  Assert-Match ([string]$pythonConfig.prepare.localCommands[-1].command) '(?:--wheel|-f wheel)' "Python local build still creates every distribution"
  Assert-Equal (@($pythonConfig.prepare.localArtifacts).Count) 0 "Python local build still requires formal artifacts"
  $pythonWorkflow = Get-Content -Raw -Encoding UTF8 (Join-Path $pythonRoot ".github\workflows\release.yml")
  Assert-Match $pythonWorkflow 'actions/setup-python@[0-9a-f]{40}\s+# v6' "Python workflow action is not pinned"
}
finally {
  Remove-TestDirectory $pythonRoot
}

$rustRoot = New-TestDirectory "rust"
try {
  Write-TestUtf8 (Join-Path $rustRoot "Cargo.toml") @'
[package]
name = "rust-fixture"
version = "1.2.3"
edition = "2021"
'@
  Write-TestUtf8 (Join-Path $rustRoot "src\lib.rs") "pub fn answer() -> u32 { 42 }`n"
  $rustDetection = (& $setupScript -Mode Detect -RepositoryRoot $rustRoot) | ConvertFrom-Json
  Assert-Equal $rustDetection.projectType "rust" "Rust fixture was not detected"
  & $setupScript -Mode Generate -RepositoryRoot $rustRoot
  & $setupScript -Mode Validate -RepositoryRoot $rustRoot
  $rustConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $rustRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $rustConfig.automation.template "rust-v1" "Rust config uses the wrong template"
  Assert-Match ([string]$rustConfig.prepare.commands[1].command) 'cargo package' "Rust package command is missing"
  Assert-Match ([string]$rustConfig.prepare.localCommands[-1].command) 'cargo build --release' "Rust local build still packages the crate"
}
finally {
  Remove-TestDirectory $rustRoot
}

$dotnetRoot = New-TestDirectory "dotnet"
try {
  Write-TestUtf8 (Join-Path $dotnetRoot "DotNetFixture.csproj") @'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PackageId>DotNet.Fixture</PackageId>
    <Version>1.2.3</Version>
  </PropertyGroup>
</Project>
'@
  $dotnetDetection = (& $setupScript -Mode Detect -RepositoryRoot $dotnetRoot) | ConvertFrom-Json
  Assert-Equal $dotnetDetection.projectType "dotnet" ".NET fixture was not detected"
  Assert-Equal $dotnetDetection.projectName "DotNet.Fixture" ".NET PackageId was not detected"
  & $setupScript -Mode Generate -RepositoryRoot $dotnetRoot
  & $setupScript -Mode Validate -RepositoryRoot $dotnetRoot
  $dotnetConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $dotnetRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $dotnetConfig.automation.template "dotnet-v1" ".NET config uses the wrong template"
  Assert-Match ([string]$dotnetConfig.prepare.localCommands[-1].command) 'dotnet build' ".NET local build still creates a NuGet package"
  Assert-Equal ([string]$dotnetConfig.prepare.localSearchRoots[0]) "bin/Release" ".NET local artifact search root is wrong"
  $dotnetWorkflow = Get-Content -Raw -Encoding UTF8 (Join-Path $dotnetRoot ".github\workflows\release.yml")
  Assert-Match $dotnetWorkflow 'actions/setup-dotnet@[0-9a-f]{40}\s+# v5' ".NET workflow action is not pinned"
  Assert-Match $dotnetWorkflow 'dotnet-version: "8\.0\.x"' ".NET SDK was not inferred from TargetFramework"
}
finally {
  Remove-TestDirectory $dotnetRoot
}

$mavenRoot = New-TestDirectory "maven"
try {
  Write-TestUtf8 (Join-Path $mavenRoot "pom.xml") @'
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>example.invalid</groupId>
  <artifactId>java-fixture</artifactId>
  <version>1.2.3</version>
</project>
'@
  $mavenDetection = (& $setupScript -Mode Detect -RepositoryRoot $mavenRoot) | ConvertFrom-Json
  Assert-Equal $mavenDetection.projectType "java" "Maven fixture was not detected as Java"
  Assert-Equal $mavenDetection.packageManager "maven" "Maven build system was not detected"
  & $setupScript -Mode Generate -RepositoryRoot $mavenRoot
  & $setupScript -Mode Validate -RepositoryRoot $mavenRoot
  $mavenConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $mavenRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $mavenConfig.automation.template "java-v1" "Maven config uses the wrong template"
  $mavenWorkflow = Get-Content -Raw -Encoding UTF8 (Join-Path $mavenRoot ".github\workflows\release.yml")
  Assert-Match $mavenWorkflow 'actions/setup-java@[0-9a-f]{40}\s+# v5' "Java workflow action is not pinned"
  Assert-Match $mavenWorkflow 'cache: maven' "Maven dependency cache is missing"
}
finally {
  Remove-TestDirectory $mavenRoot
}

$gradleRoot = New-TestDirectory "gradle"
try {
  Write-TestUtf8 (Join-Path $gradleRoot "build.gradle.kts") @'
plugins { java }
group = "example.invalid"
version = "1.2.3"
'@
  Write-TestUtf8 (Join-Path $gradleRoot "settings.gradle.kts") 'rootProject.name = "gradle-fixture"'
  $gradleDetection = (& $setupScript -Mode Detect -RepositoryRoot $gradleRoot) | ConvertFrom-Json
  Assert-Equal $gradleDetection.projectType "java" "Gradle fixture was not detected as Java"
  Assert-Equal $gradleDetection.packageManager "gradle" "Gradle build system was not detected"
  Assert-Equal $gradleDetection.projectName "gradle-fixture" "Gradle root project name was not detected"
  & $setupScript -Mode Generate -RepositoryRoot $gradleRoot
  & $setupScript -Mode Validate -RepositoryRoot $gradleRoot
  $gradleWorkflow = Get-Content -Raw -Encoding UTF8 (Join-Path $gradleRoot ".github\workflows\release.yml")
  Assert-Match $gradleWorkflow 'cache: gradle' "Gradle dependency cache is missing"
  Assert-Match $gradleWorkflow 'build/libs' "Gradle artifact directory is wrong"
}
finally {
  Remove-TestDirectory $gradleRoot
}

$cmakeRoot = New-TestDirectory "cmake"
try {
  Write-TestUtf8 (Join-Path $cmakeRoot "CMakeLists.txt") @'
cmake_minimum_required(VERSION 3.24)
project(cmake_fixture VERSION 1.2.3 LANGUAGES CXX)
add_executable(cmake_fixture main.cpp)
'@
  Write-TestUtf8 (Join-Path $cmakeRoot "main.cpp") "int main() { return 0; }`n"
  $cmakeDetection = (& $setupScript -Mode Detect -RepositoryRoot $cmakeRoot) | ConvertFrom-Json
  Assert-Equal $cmakeDetection.projectType "cmake" "CMake fixture was not detected"
  Assert-Equal $cmakeDetection.projectName "cmake_fixture" "CMake project name was not detected"
  & $setupScript -Mode Generate -RepositoryRoot $cmakeRoot
  & $setupScript -Mode Validate -RepositoryRoot $cmakeRoot
  $cmakeConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $cmakeRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $cmakeConfig.automation.template "cmake-v1" "CMake config uses the wrong template"
  Assert-Equal @($cmakeConfig.publish.release.requiredAssets).Count 6 "CMake config does not validate six platform archives"
  $cmakeWorkflow = Get-Content -Raw -Encoding UTF8 (Join-Path $cmakeRoot ".github\workflows\release.yml")
  Assert-Match $cmakeWorkflow 'windows-11-arm' "CMake workflow is missing Windows ARM64"
  Assert-Match $cmakeWorkflow 'cmake_fixture' "CMake executable target was not rendered"
}
finally {
  Remove-TestDirectory $cmakeRoot
}

$flutterRoot = New-TestDirectory "flutter"
try {
  Write-TestUtf8 (Join-Path $flutterRoot "pubspec.yaml") @'
name: flutter_fixture
version: 1.2.3+4
environment:
  sdk: ">=3.0.0 <4.0.0"
'@
  New-Item -ItemType Directory -Path (Join-Path $flutterRoot "test") | Out-Null
  $flutterDetection = (& $setupScript -Mode Detect -RepositoryRoot $flutterRoot) | ConvertFrom-Json
  Assert-Equal $flutterDetection.projectType "flutter" "Flutter fixture was not detected"
  Assert-Equal $flutterDetection.version "1.2.3" "Flutter build metadata was not normalized"
  & $setupScript -Mode Generate -RepositoryRoot $flutterRoot
  & $setupScript -Mode Validate -RepositoryRoot $flutterRoot
  $flutterConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $flutterRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $flutterConfig.automation.template "flutter-v1" "Flutter config uses the wrong template"
  Assert-Equal @($flutterConfig.publish.release.requiredAssets).Count 7 "Flutter config does not validate all packages"
  $flutterWorkflow = Get-Content -Raw -Encoding UTF8 (Join-Path $flutterRoot ".github\workflows\release.yml")
  Assert-Match $flutterWorkflow 'subosito/flutter-action@[0-9a-f]{40}\s+# v2' "Flutter setup action is not pinned"
  Assert-Match $flutterWorkflow 'android-aab' "Flutter workflow is missing Android App Bundle"
}
finally {
  Remove-TestDirectory $flutterRoot
}

$androidRoot = New-TestDirectory "android"
try {
  Write-TestUtf8 (Join-Path $androidRoot "settings.gradle.kts") 'rootProject.name = "android-fixture"'
  Write-TestUtf8 (Join-Path $androidRoot "build.gradle.kts") 'plugins { id("com.android.application") version "8.7.0" apply false }'
  Write-TestUtf8 (Join-Path $androidRoot "app\build.gradle.kts") @'
plugins { id("com.android.application") }
android {
  namespace = "invalid.example.fixture"
  defaultConfig {
    applicationId = "invalid.example.fixture"
    versionCode = 1
    versionName = "1.2.3"
  }
}
'@
  Write-TestUtf8 (Join-Path $androidRoot "gradlew") "#!/bin/sh`n"
  Write-TestUtf8 (Join-Path $androidRoot "gradlew.bat") "@echo off`r`n"
  $androidDetection = (& $setupScript -Mode Detect -RepositoryRoot $androidRoot) | ConvertFrom-Json
  Assert-Equal $androidDetection.projectType "android" "Android fixture was not detected before generic Java"
  Assert-Equal $androidDetection.buildPath "app" "Android application module was not detected"
  & $setupScript -Mode Generate -RepositoryRoot $androidRoot
  & $setupScript -Mode Validate -RepositoryRoot $androidRoot
  $androidConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $androidRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $androidConfig.automation.template "android-v1" "Android config uses the wrong template"
  Assert-Equal @($androidConfig.publish.release.requiredAssets).Count 2 "Android config does not validate APK and AAB"
  $androidWorkflow = Get-Content -Raw -Encoding UTF8 (Join-Path $androidRoot ".github\workflows\release.yml")
  Assert-Match $androidWorkflow 'gradle/actions/setup-gradle@[0-9a-f]{40}\s+# v6' "Android Gradle action is not pinned"
}
finally {
  Remove-TestDirectory $androidRoot
}

$electronRoot = New-TestDirectory "electron"
try {
  Write-TestUtf8 (Join-Path $electronRoot "package.json") @'
{
  "name": "electron-fixture",
  "productName": "Electron Fixture",
  "version": "1.2.3",
  "devDependencies": {"electron": "^40.0.0"},
  "scripts": {"test": "node --test", "dist": "electron-builder"},
  "build": {"directories": {"output": "release-build"}}
}
'@
  Write-TestUtf8 (Join-Path $electronRoot "package-lock.json") '{"name":"electron-fixture","version":"1.2.3","lockfileVersion":3,"packages":{"":{"name":"electron-fixture","version":"1.2.3"}}}'
  $electronDetection = (& $setupScript -Mode Detect -RepositoryRoot $electronRoot) | ConvertFrom-Json
  Assert-Equal $electronDetection.projectType "electron" "Electron fixture was detected as generic Node.js"
  & $setupScript -Mode Generate -RepositoryRoot $electronRoot
  & $setupScript -Mode Validate -RepositoryRoot $electronRoot
  $electronConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $electronRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $electronConfig.automation.template "electron-v1" "Electron config uses the wrong template"
  Assert-Equal ([string]$electronConfig.prepare.localSearchRoots[0]) "release-build" "Electron local output discovery ignores the configured directory"
  Assert-Equal @($electronConfig.publish.release.requiredAssets).Count 6 "Electron config does not validate six platform archives"
  $electronWorkflow = Get-Content -Raw -Encoding UTF8 (Join-Path $electronRoot ".github\workflows\release.yml")
  Assert-Match $electronWorkflow 'release-build/\*' "Electron output directory was not rendered"
}
finally {
  Remove-TestDirectory $electronRoot
}

$dockerRoot = New-TestDirectory "docker"
try {
  Write-TestUtf8 (Join-Path $dockerRoot "Dockerfile") @'
FROM scratch
LABEL org.opencontainers.image.title="docker-fixture"
'@
  $dockerDetection = (& $setupScript -Mode Detect -RepositoryRoot $dockerRoot) | ConvertFrom-Json
  Assert-Equal $dockerDetection.projectType "docker" "Docker-only fixture was not detected"
  & $setupScript -Mode Generate -RepositoryRoot $dockerRoot
  & $setupScript -Mode Validate -RepositoryRoot $dockerRoot
  Assert-Equal ([IO.File]::ReadAllText((Join-Path $dockerRoot "VERSION")).Trim()) "0.1.0" "Docker VERSION default is wrong"
  $dockerConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $dockerRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $dockerConfig.automation.template "docker-v1" "Docker config uses the wrong template"
  $dockerWorkflow = Get-Content -Raw -Encoding UTF8 (Join-Path $dockerRoot ".github\workflows\release.yml")
  Assert-Match $dockerWorkflow 'packages: write' "Docker workflow cannot publish GHCR packages"
  Assert-Match $dockerWorkflow 'docker/build-push-action@[0-9a-f]{40}\s+# v7' "Docker build action is not pinned"
  Assert-Match $dockerWorkflow 'linux/amd64,linux/arm64' "Docker workflow is not multi-architecture"
}
finally {
  Remove-TestDirectory $dockerRoot
}

$ambiguousRoot = New-TestDirectory "ambiguous"
try {
  Write-TestUtf8 (Join-Path $ambiguousRoot "package.json") '{"name":"ambiguous","version":"1.0.0"}'
  Write-TestUtf8 (Join-Path $ambiguousRoot "go.mod") "module example.invalid/ambiguous`n`ngo 1.24`n"
  Assert-Throws {
    & $setupScript -Mode Detect -RepositoryRoot $ambiguousRoot
  } "detection is ambiguous" "Mixed Node and Go project must require an explicit project type"
}
finally {
  Remove-TestDirectory $ambiguousRoot
}

$humanWorkflowRoot = New-TestDirectory "human-workflow"
try {
  Write-TestUtf8 (Join-Path $humanWorkflowRoot "package.json") '{"name":"protected","version":"1.0.0"}'
  Write-TestUtf8 (Join-Path $humanWorkflowRoot ".github\workflows\release.yml") @'
name: Human Release
on: workflow_dispatch
jobs: {}
'@
  Assert-Throws {
    & $setupScript -Mode Generate -RepositoryRoot $humanWorkflowRoot
  } "Refusing to overwrite human-managed workflow" "Generator overwrote a human workflow"
  if (Test-Path -LiteralPath (Join-Path $humanWorkflowRoot ".codex-release.json")) {
    throw "Generator wrote config before checking the workflow conflict"
  }
}
finally {
  Remove-TestDirectory $humanWorkflowRoot
}

$localOnlyRoot = New-TestDirectory "local-only"
try {
  Write-TestUtf8 (Join-Path $localOnlyRoot "package.json") '{"name":"local-only","version":"1.0.0"}'
  $localOnlyWorkflow = @'
name: Human CI
on: workflow_dispatch
jobs: {}
'@
  $localOnlyWorkflowPath = Join-Path $localOnlyRoot ".github\workflows\release.yml"
  Write-TestUtf8 $localOnlyWorkflowPath $localOnlyWorkflow
  $workflowHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $localOnlyWorkflowPath).Hash
  & $setupScript -Mode GenerateLocal -RepositoryRoot $localOnlyRoot
  & git -C $localOnlyRoot check-ignore -q --no-index -- .codex-release.json
  if ($LASTEXITCODE -ne 0) { throw "GenerateLocal did not ignore the local config" }
  $localOnlyConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $localOnlyRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $localOnlyConfig.automation.localOnly $true "GenerateLocal did not mark the local-only config"
  Assert-Equal $localOnlyConfig.automation.managedWorkflow $false "GenerateLocal incorrectly marked a release workflow as managed"
  Assert-Equal $localOnlyConfig.publish.release.mode "none" "GenerateLocal enabled GitHub publication"
  if ($localOnlyConfig.publish.workflow) { throw "GenerateLocal configured a GitHub workflow" }
  Assert-Equal (Get-FileHash -Algorithm SHA256 -LiteralPath $localOnlyWorkflowPath).Hash $workflowHash "GenerateLocal changed a human workflow"
  if (Test-Path -LiteralPath (Join-Path $localOnlyRoot ".github\workflows\auto-release.yml")) {
    throw "GenerateLocal created a release workflow"
  }
  $localConfigHash = (Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $localOnlyRoot ".codex-release.json")).Hash
  & $setupScript -Mode GenerateLocal -RepositoryRoot $localOnlyRoot
  Assert-Equal (Get-FileHash -Algorithm SHA256 -LiteralPath (Join-Path $localOnlyRoot ".codex-release.json")).Hash $localConfigHash "GenerateLocal is not idempotent"
  & $setupScript -Mode Generate -RepositoryRoot $localOnlyRoot -ExistingWorkflowPolicy CreateSeparate
  $upgradedLocalConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $localOnlyRoot ".codex-release.json") | ConvertFrom-Json
  if ($upgradedLocalConfig.automation.localOnly) { throw "Full generation did not remove the local-only marker" }
  Assert-Equal $upgradedLocalConfig.publish.release.mode "publish-draft" "Local-only config did not upgrade to formal publication"
  if (-not (Test-Path -LiteralPath (Join-Path $localOnlyRoot ".github\workflows\auto-release.yml") -PathType Leaf)) {
    throw "Local-only config upgrade did not create a separate release workflow"
  }
  Assert-Equal (Get-FileHash -Algorithm SHA256 -LiteralPath $localOnlyWorkflowPath).Hash $workflowHash "Local-only upgrade changed the human workflow"
}
finally {
  Remove-TestDirectory $localOnlyRoot
}

$separateWorkflowRoot = New-TestDirectory "separate-workflow"
try {
  Write-TestUtf8 (Join-Path $separateWorkflowRoot "package.json") '{"name":"separate","version":"1.0.0"}'
  $humanWorkflow = @'
name: Existing CI
on: workflow_dispatch
jobs: {}
'@
  Write-TestUtf8 (Join-Path $separateWorkflowRoot ".github\workflows\release.yml") $humanWorkflow
  & $setupScript -Mode Generate -RepositoryRoot $separateWorkflowRoot -ExistingWorkflowPolicy CreateSeparate
  Assert-Equal ([IO.File]::ReadAllText((Join-Path $separateWorkflowRoot ".github\workflows\release.yml"))) $humanWorkflow "Separate policy changed the human workflow"
  $separateConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $separateWorkflowRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $separateConfig.automation.workflowFile ".github/workflows/auto-release.yml" "Separate policy selected the wrong workflow"
  Assert-Equal $separateConfig.automation.managedWorkflow $true "Separate workflow must remain generator-managed"
  Assert-Match (Get-Content -Raw -Encoding UTF8 (Join-Path $separateWorkflowRoot ".github\workflows\auto-release.yml")) '^# Generated by Auto Release' "Separate managed workflow was not generated"
}
finally {
  Remove-TestDirectory $separateWorkflowRoot
}

$reuseWorkflowRoot = New-TestDirectory "reuse-workflow"
try {
  Write-TestUtf8 (Join-Path $reuseWorkflowRoot "package.json") '{"name":"reuse","version":"1.0.0"}'
  Write-TestUtf8 (Join-Path $reuseWorkflowRoot ".github\workflows\release.yml") @'
name: Human Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: gh release create "$GITHUB_REF_NAME" package.tgz --draft
'@
  & $setupScript -Mode Generate -RepositoryRoot $reuseWorkflowRoot -ExistingWorkflowPolicy ReuseCompatible
  $reuseConfig = Get-Content -Raw -Encoding UTF8 (Join-Path $reuseWorkflowRoot ".codex-release.json") | ConvertFrom-Json
  Assert-Equal $reuseConfig.automation.workflowFile ".github/workflows/release.yml" "Reuse policy changed the human workflow path"
  Assert-Equal $reuseConfig.automation.managedWorkflow $false "Reused human workflow must not become generator-managed"
  Assert-Equal $reuseConfig.publish.workflow.name "Human Release" "Reused human workflow name was not recorded"
  if (Test-Path -LiteralPath (Join-Path $reuseWorkflowRoot ".github\workflows\project-release.yml")) {
    throw "Reuse policy generated an unnecessary separate workflow"
  }
}
finally {
  Remove-TestDirectory $reuseWorkflowRoot
}

$localDiscoveryRoot = New-TestDirectory "local-discovery"
try {
  Write-TestUtf8 (Join-Path $localDiscoveryRoot "package.json") '{"name":"detected-app","version":"1.0.0"}'
  Write-TestUtf8 (Join-Path $localDiscoveryRoot ".codex-release.json") @'
{
  "schemaVersion": 1,
  "projectType": "tauri",
  "projectName": "DetectedApp",
  "branch": "main",
  "remote": "origin",
  "tagPrefix": "v",
  "version": {
    "read": {
      "path": "package.json",
      "pattern": "\\\"version\\\"\\s*:\\s*\\\"(?<version>\\d+\\.\\d+\\.\\d+)\\\""
    },
    "updates": []
  },
  "prepare": {
    "parallel": false,
    "commands": [
      {
        "name": "Build discoverable program",
        "command": "if not exist src-tauri\\target\\release mkdir src-tauri\\target\\release && echo detected>src-tauri\\target\\release\\DetectedApp.exe"
      }
    ],
    "artifacts": []
  },
  "publish": {"release":{"mode":"none"}}
}
'@
  & $script -Mode LocalBuild -RepositoryRoot $localDiscoveryRoot
  $discoveredOutput = Join-Path $localDiscoveryRoot "output\DetectedApp.exe"
  if (-not (Test-Path -LiteralPath $discoveredOutput -PathType Leaf)) {
    throw "LocalBuild did not discover and materialize an undeclared local program"
  }
  Assert-Equal (Get-Content -Raw -Encoding UTF8 $discoveredOutput).Trim() "detected" "Discovered local output has the wrong content"
}
finally {
  Remove-TestDirectory $localDiscoveryRoot
}
