[CmdletBinding()]
param(
  [Parameter(Mandatory)]
  [ValidateSet("Detect", "GenerateLocal", "Generate", "Validate")]
  [string]$Mode,

  [ValidateSet("auto", "tauri", "node", "go", "python", "rust", "dotnet", "java", "cmake", "flutter", "android", "electron", "docker")]
  [string]$ProjectType = "auto",

  [string]$RepositoryRoot = (Get-Location).Path,

  [string]$ConfigPath = ".codex-release.json",

  [string]$WorkflowPath = ".github/workflows/release.yml",

  [ValidateSet("Stop", "CreateSeparate", "ReuseCompatible")]
  [string]$ExistingWorkflowPolicy = "Stop",

  [string]$SeparateWorkflowPath = ".github/workflows/auto-release.yml"
)

$ErrorActionPreference = "Stop"
$script:GeneratorName = "auto-release"
$script:LegacyGeneratorNames = @("project-release-automator")
$script:WorkflowMarker = "# Generated by Auto Release"
$script:LegacyWorkflowMarkers = @("# Generated by Project Release Automator")
$script:ResolvedRepositoryRoot = $null
$profileScript = Join-Path $PSScriptRoot "project-profiles.ps1"
if (-not (Test-Path -LiteralPath $profileScript -PathType Leaf)) { throw "Project profile module missing: $profileScript" }
. $profileScript
$generationScript = Join-Path $PSScriptRoot "project-generation.ps1"
if (-not (Test-Path -LiteralPath $generationScript -PathType Leaf)) { throw "Project generation module missing: $generationScript" }
. $generationScript

function Get-OptionalProperty($Object, [string]$Name, $Default = $null) {
  if ($null -eq $Object) { return $Default }
  $property = $Object.PSObject.Properties[$Name]
  if ($null -eq $property) { return $Default }
  return $property.Value
}

function Get-RequiredProperty($Object, [string]$Name, [string]$Context) {
  $value = Get-OptionalProperty $Object $Name
  if ($null -eq $value -or ($value -is [string] -and [string]::IsNullOrWhiteSpace($value))) {
    throw "Missing required config field: $Context.$Name"
  }
  return $value
}

function Get-NormalizedPath([string]$Path) {
  return [IO.Path]::GetFullPath($Path).TrimEnd(
    [IO.Path]::DirectorySeparatorChar,
    [IO.Path]::AltDirectorySeparatorChar
  )
}

function Resolve-RepositoryFile([string]$RelativePath) {
  if ([IO.Path]::IsPathRooted($RelativePath)) {
    throw "Generated path must be relative: $RelativePath"
  }
  $fullPath = Get-NormalizedPath (Join-Path $script:ResolvedRepositoryRoot $RelativePath)
  $prefix = $script:ResolvedRepositoryRoot + [IO.Path]::DirectorySeparatorChar
  if (-not $fullPath.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)) {
    throw "Generated path escapes repository root: $RelativePath"
  }
  return $fullPath
}

function Read-JsonFile([string]$Path, [string]$Label) {
  try {
    return Get-Content -Raw -Encoding UTF8 -LiteralPath $Path | ConvertFrom-Json
  }
  catch {
    throw "$Label is not valid JSON: $Path. $($_.Exception.Message)"
  }
}

function Get-GitValue([string[]]$Arguments) {
  $output = & git -C $script:ResolvedRepositoryRoot @Arguments 2>$null
  if ($LASTEXITCODE -ne 0) { return $null }
  return (($output | Out-String).Trim())
}

function Render-Template([string]$Path, [hashtable]$Tokens) {
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { throw "Workflow template not found: $Path" }
  $content = [IO.File]::ReadAllText($Path)
  foreach ($entry in $Tokens.GetEnumerator()) {
    $content = $content.Replace("{{$($entry.Key)}}", [string]$entry.Value)
  }
  if ($content -match '\{\{[A-Z][A-Z0-9_]*\}\}') {
    throw "Workflow template contains unresolved token: $($Matches[0])"
  }
  return $content
}

function Assert-ManagedConfigOrAbsent([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return }
  $existing = Read-JsonFile $Path "Existing release config"
  $automation = Get-OptionalProperty $existing "automation"
  if (-not (Test-ManagedGeneratorName ([string](Get-OptionalProperty $automation "generator" "")))) {
    throw "Refusing to overwrite human-managed release config: $Path"
  }
}

function Test-ManagedGeneratorName([string]$Name) {
  return $Name -eq $script:GeneratorName -or $Name -in $script:LegacyGeneratorNames
}

function Test-ManagedWorkflowContent([string]$Content) {
  foreach ($marker in @($script:WorkflowMarker) + $script:LegacyWorkflowMarkers) {
    if ($Content.StartsWith($marker, [StringComparison]::Ordinal)) { return $true }
  }
  return $false
}

function Assert-ManagedWorkflowOrAbsent([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return }
  $content = [IO.File]::ReadAllText($Path)
  if (-not (Test-ManagedWorkflowContent $content)) {
    throw "Refusing to overwrite human-managed workflow: $Path"
  }
}

function Test-ManagedWorkflow([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return $false }
  return Test-ManagedWorkflowContent ([IO.File]::ReadAllText($Path))
}

function Assert-CompatibleWorkflowContent([string]$Content, [string]$ProjectType) {
  $workflowName = Get-WorkflowName $Content
  if ($Content -notmatch '(?ms)^on:\s*\r?\n\s+push:\s*\r?\n\s+tags:') {
    throw "Existing workflow is not compatible: tag push trigger is missing"
  }
  if ($Content -notmatch '(?m)^\s+contents:\s*write\s*$') {
    throw "Existing workflow is not compatible: contents write permission is missing"
  }
  if ($Content -notmatch '(?i)(releaseDraft:\s*true|gh\s+release\s+create[^\r\n]*(?:\r?\n[^\r\n]*)*?--draft)') {
    throw "Existing workflow is not compatible: draft Release creation is missing"
  }
  if ($ProjectType -eq "docker") {
    if ($Content -notmatch '(?m)^\s+packages:\s*write\s*$') {
      throw "Existing Docker workflow is not compatible: packages write permission is missing"
    }
    if ($Content -notmatch 'docker/build-push-action@(?:v7|[0-9a-f]{40})' -or $Content -notmatch '(?m)^\s+push:\s*true\s*$') {
      throw "Existing Docker workflow is not compatible: image push is missing"
    }
  }
  return $workflowName
}

function Write-AtomicUtf8([string]$Path, [string]$Content) {
  $directory = Split-Path -Parent $Path
  if (-not (Test-Path -LiteralPath $directory -PathType Container)) {
    New-Item -ItemType Directory -Force -Path $directory | Out-Null
  }
  $temporary = Join-Path $directory ((Split-Path -Leaf $Path) + ".tmp." + [guid]::NewGuid().ToString("N"))
  $backup = Join-Path $directory ((Split-Path -Leaf $Path) + ".bak." + [guid]::NewGuid().ToString("N"))
  try {
    [IO.File]::WriteAllText($temporary, $Content, [Text.UTF8Encoding]::new($false))
    if (Test-Path -LiteralPath $Path -PathType Leaf) {
      [IO.File]::Replace($temporary, $Path, $backup)
    }
    else {
      [IO.File]::Move($temporary, $Path)
    }
  }
  finally {
    if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary -Force }
    if (Test-Path -LiteralPath $backup) { Remove-Item -LiteralPath $backup -Force }
  }
}

function ConvertTo-GitIgnoreLiteralPath([string]$RelativePath) {
  $normalized = $RelativePath.Replace("\", "/").TrimStart("/")
  $builder = [Text.StringBuilder]::new()
  foreach ($character in $normalized.ToCharArray()) {
    if ($character -in @([char]' ', [char]'#', [char]'!', [char]'*', [char]'?', [char]'[', [char]']')) {
      [void]$builder.Append([char]'\')
    }
    [void]$builder.Append($character)
  }
  return "/$($builder.ToString())"
}

function Get-LocalConfigIgnoreFile {
  $configFile = Resolve-RepositoryFile $ConfigPath
  $relativeConfigPath = Get-RelativeRepositoryPath $configFile
  $pattern = ConvertTo-GitIgnoreLiteralPath $relativeConfigPath
  $ignoreFile = Resolve-RepositoryFile ".gitignore"
  $existingText = if (Test-Path -LiteralPath $ignoreFile -PathType Leaf) { [IO.File]::ReadAllText($ignoreFile) } else { "" }
  $hasExactRule = @($existingText -split "`r?`n" | Where-Object { $_.Trim() -ceq $pattern }).Count -gt 0
  if ($hasExactRule) { return $null }

  $trimmed = $existingText.TrimEnd("`r", "`n")
  $addition = "# Auto Release local configuration`n$pattern`n"
  $content = if ($trimmed) { "$trimmed`n`n$addition" } else { $addition }
  return [pscustomobject]@{ Path = $ignoreFile; Content = $content }
}

function Invoke-Generate($Profile) {
  $configFile = Resolve-RepositoryFile $ConfigPath
  $selectedWorkflowPath = $WorkflowPath
  $workflowFile = Resolve-RepositoryFile $selectedWorkflowPath
  $reuseHumanWorkflow = $false
  $humanWorkflowName = $null

  if ((Test-Path -LiteralPath $workflowFile -PathType Leaf) -and -not (Test-ManagedWorkflow $workflowFile)) {
    if ($ExistingWorkflowPolicy -eq "CreateSeparate") {
      if ($SeparateWorkflowPath.Replace("\", "/") -eq $WorkflowPath.Replace("\", "/")) {
        throw "Separate workflow path must differ from the existing workflow path"
      }
      $selectedWorkflowPath = $SeparateWorkflowPath
      $workflowFile = Resolve-RepositoryFile $selectedWorkflowPath
      if ((Test-Path -LiteralPath $workflowFile -PathType Leaf) -and -not (Test-ManagedWorkflow $workflowFile)) {
        throw "Refusing to overwrite human-managed separate workflow: $workflowFile"
      }
      Write-Host "Preserving human workflow; using separate release workflow: $selectedWorkflowPath"
    }
    elseif ($ExistingWorkflowPolicy -eq "ReuseCompatible") {
      $humanWorkflowName = Assert-CompatibleWorkflowContent ([IO.File]::ReadAllText($workflowFile)) $Profile.ProjectType
      $reuseHumanWorkflow = $true
      Write-Host "Reusing compatible human-managed workflow: $selectedWorkflowPath"
    }
    else {
      throw "Refusing to overwrite human-managed workflow: $workflowFile"
    }
  }

  $bundle = New-GenerationBundle $Profile $selectedWorkflowPath (-not $reuseHumanWorkflow)
  if ($reuseHumanWorkflow) {
    $bundle.Config.publish.workflow.name = $humanWorkflowName
  }
  $configContent = ($bundle.Config | ConvertTo-Json -Depth 20) + "`n"
  $workflowContent = $null
  if (-not $reuseHumanWorkflow) {
    $workflowContent = Render-Template $bundle.TemplateFile $bundle.Tokens
    if (-not $workflowContent.EndsWith("`n")) { $workflowContent += "`n" }
  }

  Assert-ManagedConfigOrAbsent $configFile
  if (-not $reuseHumanWorkflow) {
    Assert-ManagedWorkflowOrAbsent $workflowFile
  }
  foreach ($additional in $bundle.AdditionalFiles) {
    $additionalPath = Resolve-RepositoryFile $additional.RelativePath
    if (
      (Test-Path -LiteralPath $additionalPath -PathType Leaf) -and
      [IO.File]::ReadAllText($additionalPath) -cne $additional.Content
    ) {
      throw "Refusing to overwrite existing generated support file: $additionalPath"
    }
  }

  $desired = @()
  $ignoreFile = Get-LocalConfigIgnoreFile
  if ($ignoreFile) { $desired += $ignoreFile }
  $desired += [pscustomobject]@{ Path = $configFile; Content = $configContent }
  if (-not $reuseHumanWorkflow) {
    $desired += [pscustomobject]@{ Path = $workflowFile; Content = $workflowContent }
  }
  foreach ($additional in $bundle.AdditionalFiles) {
    $desired += [pscustomobject]@{ Path = Resolve-RepositoryFile $additional.RelativePath; Content = $additional.Content }
  }
  foreach ($file in $desired) {
    if ((Test-Path -LiteralPath $file.Path -PathType Leaf) -and [IO.File]::ReadAllText($file.Path) -ceq $file.Content) {
      Write-Host "Unchanged: $($file.Path)"
    }
    else {
      Write-AtomicUtf8 $file.Path $file.Content
      Write-Host "Generated: $($file.Path)"
    }
  }
  Invoke-Validate
}

function Invoke-GenerateLocal($Profile) {
  $configFile = Resolve-RepositoryFile $ConfigPath
  $bundle = New-GenerationBundle $Profile $WorkflowPath $false
  $bundle.Config.automation | Add-Member -NotePropertyName localOnly -NotePropertyValue $true -Force
  $bundle.Config.publish.workflow = $null
  $bundle.Config.publish.release.mode = "none"
  $configContent = ($bundle.Config | ConvertTo-Json -Depth 20) + "`n"

  Assert-ManagedConfigOrAbsent $configFile
  foreach ($additional in $bundle.AdditionalFiles) {
    $additionalPath = Resolve-RepositoryFile $additional.RelativePath
    if (
      (Test-Path -LiteralPath $additionalPath -PathType Leaf) -and
      [IO.File]::ReadAllText($additionalPath) -cne $additional.Content
    ) {
      throw "Refusing to overwrite existing generated support file: $additionalPath"
    }
  }

  $desired = @()
  $ignoreFile = Get-LocalConfigIgnoreFile
  if ($ignoreFile) { $desired += $ignoreFile }
  $desired += [pscustomobject]@{ Path = $configFile; Content = $configContent }
  foreach ($additional in $bundle.AdditionalFiles) {
    $desired += [pscustomobject]@{ Path = Resolve-RepositoryFile $additional.RelativePath; Content = $additional.Content }
  }
  foreach ($file in $desired) {
    if ((Test-Path -LiteralPath $file.Path -PathType Leaf) -and [IO.File]::ReadAllText($file.Path) -ceq $file.Content) {
      Write-Host "Unchanged: $($file.Path)"
    }
    else {
      Write-AtomicUtf8 $file.Path $file.Content
      Write-Host "Generated local build config: $($file.Path)"
    }
  }
  Invoke-Validate
}

function Get-WorkflowName([string]$Content) {
  $match = [regex]::Match($Content, '(?m)^name:\s*(?<name>[^\r\n#]+)')
  if (-not $match.Success) { throw "Workflow does not declare a name" }
  return $match.Groups["name"].Value.Trim().Trim('"').Trim("'")
}

function Invoke-Validate {
  $configFile = Resolve-RepositoryFile $ConfigPath
  if (-not (Test-Path -LiteralPath $configFile -PathType Leaf)) { throw "Release config not found: $configFile" }
  $configText = [IO.File]::ReadAllText($configFile)
  if ($configText -match '\{\{[A-Z][A-Z0-9_]*\}\}') { throw "Release config contains unresolved token: $($Matches[0])" }
  $config = Read-JsonFile $configFile "Release config"
  $schemaVersion = [int](Get-RequiredProperty $config "schemaVersion" "root")
  if ($schemaVersion -notin @(1, 2)) { throw "Unsupported release config schemaVersion: $schemaVersion" }
  if ($schemaVersion -eq 2) {
    $configuredProjectType = [string](Get-RequiredProperty $config "projectType" "root")
    if ($configuredProjectType -notin @("tauri", "node", "go", "python", "rust", "dotnet", "java", "cmake", "flutter", "android", "electron", "docker")) { throw "Unsupported projectType: $configuredProjectType" }
  }
  foreach ($name in @("projectName", "branch", "remote")) { Get-RequiredProperty $config $name "root" | Out-Null }
  $githubRepository = [string](Get-OptionalProperty $config "githubRepository" "")
  if ($githubRepository -and $githubRepository -notmatch '^(?:[^/\s]+/)?[^/\s]+/[^/\s]+$') {
    throw "githubRepository must use OWNER/REPO or HOST/OWNER/REPO"
  }

  $version = Get-RequiredProperty $config "version" "root"
  $read = Get-RequiredProperty $version "read" "version"
  $readPath = [string](Get-RequiredProperty $read "path" "version.read")
  $readPattern = [string](Get-RequiredProperty $read "pattern" "version.read")
  try { $readRegex = [regex]::new($readPattern) } catch { throw "version.read.pattern is invalid: $($_.Exception.Message)" }
  if ($readRegex.GetGroupNames() -notcontains "version") { throw "version.read.pattern must contain a named 'version' capture group" }
  $versionFile = Resolve-RepositoryFile $readPath
  if (-not (Test-Path -LiteralPath $versionFile -PathType Leaf)) { throw "Version source not found: $versionFile" }
  $versionMatch = $readRegex.Match([IO.File]::ReadAllText($versionFile))
  if (-not $versionMatch.Success -or $versionMatch.Groups["version"].Value -notmatch '^\d+\.\d+\.\d+$') {
    throw "Version source does not match version.read.pattern: $readPath"
  }
  foreach ($update in @(Get-OptionalProperty $version "updates" @())) {
    $updatePath = [string](Get-RequiredProperty $update "path" "version.updates[]")
    $updateFile = Resolve-RepositoryFile $updatePath
    if (-not (Test-Path -LiteralPath $updateFile -PathType Leaf)) { throw "Version update file not found: $updateFile" }
    try { [regex]::new([string](Get-RequiredProperty $update "pattern" "version.updates[]")) | Out-Null }
    catch { throw "Invalid version update pattern for ${updatePath}: $($_.Exception.Message)" }
  }

  $commit = Get-OptionalProperty $config "commit"
  if ($commit) {
    $commitPolicy = [string](Get-OptionalProperty $commit "policy" "conventional")
    if ($commitPolicy -notin @("auto", "conventional", "off")) { throw "Unsupported commit.policy: $commitPolicy" }
    $analyzeCount = [int](Get-OptionalProperty $commit "analyzeCount" 30)
    $minimumSamples = [int](Get-OptionalProperty $commit "minimumSamples" 3)
    $confidenceThreshold = [double](Get-OptionalProperty $commit "confidenceThreshold" 0.6)
    $fallback = [string](Get-OptionalProperty $commit "fallback" "conventional")
    if ($analyzeCount -lt 1) { throw "commit.analyzeCount must be positive" }
    if ($minimumSamples -lt 1) { throw "commit.minimumSamples must be positive" }
    if ($minimumSamples -gt $analyzeCount) { throw "commit.minimumSamples must not exceed commit.analyzeCount" }
    if ($confidenceThreshold -le 0 -or $confidenceThreshold -gt 1) { throw "commit.confidenceThreshold must be greater than 0 and at most 1" }
    if ($fallback -ne "conventional") { throw "commit.fallback must be conventional" }
  }

  $prepare = Get-RequiredProperty $config "prepare" "root"
  $localOutputDirectory = [string](Get-OptionalProperty $prepare "localOutputDirectory" "output")
  if ([string]::IsNullOrWhiteSpace($localOutputDirectory) -or $localOutputDirectory -match '\{(?:version|tag)\}') {
    throw "prepare.localOutputDirectory must be a stable path without version or tag tokens"
  }
  Resolve-RepositoryFile $localOutputDirectory | Out-Null
  foreach ($commandProperty in @("bootstrapCommands", "localCommands", "commands")) {
    foreach ($command in @(Get-OptionalProperty $prepare $commandProperty @())) {
      Get-RequiredProperty $command "name" "prepare.$commandProperty[]" | Out-Null
      Get-RequiredProperty $command "command" "prepare.$commandProperty[]" | Out-Null
    }
  }
  foreach ($artifactProperty in @("localArtifacts", "artifacts")) {
    foreach ($artifact in @(Get-OptionalProperty $prepare $artifactProperty @())) {
      Get-RequiredProperty $artifact "source" "prepare.$artifactProperty[]" | Out-Null
    }
  }
  foreach ($pathProperty in @("bootstrapInputs", "bootstrapRequiredPaths", "localSearchRoots")) {
    foreach ($relativePath in @(Get-OptionalProperty $prepare $pathProperty @())) {
      if ([string]::IsNullOrWhiteSpace([string]$relativePath)) { throw "prepare.$pathProperty[] must not be empty" }
      Resolve-RepositoryFile ([string]$relativePath) | Out-Null
    }
  }

  $publish = Get-RequiredProperty $config "publish" "root"
  $release = Get-RequiredProperty $publish "release" "publish"
  $releaseMode = [string](Get-RequiredProperty $release "mode" "publish.release")
  if ($releaseMode -notin @("publish-draft", "create", "none")) { throw "Unsupported publish.release.mode: $releaseMode" }
  $workflowConfig = Get-OptionalProperty $publish "workflow"
  $automation = Get-OptionalProperty $config "automation"
  $managed = [bool](Get-OptionalProperty $automation "managedWorkflow" $false)
  if ($schemaVersion -eq 2 -and $managed) {
    if (-not (Test-ManagedGeneratorName ([string](Get-OptionalProperty $automation "generator" "")))) { throw "Managed config generator is not recognized" }
    Get-RequiredProperty $automation "template" "automation" | Out-Null
    Get-RequiredProperty $automation "workflowFile" "automation" | Out-Null
  }

  if ($workflowConfig -or $managed) {
    $configuredWorkflowPath = [string](Get-OptionalProperty $automation "workflowFile" $WorkflowPath)
    $workflowFile = Resolve-RepositoryFile $configuredWorkflowPath
    if (-not (Test-Path -LiteralPath $workflowFile -PathType Leaf)) { throw "Release workflow not found: $workflowFile" }
    $workflow = [IO.File]::ReadAllText($workflowFile)
    if ($workflow -match '\{\{[A-Z][A-Z0-9_]*\}\}') { throw "Workflow contains unresolved token: $($Matches[0])" }
    if ($managed) {
      if (-not (Test-ManagedWorkflowContent $workflow)) { throw "Managed workflow marker is missing" }
      $template = [regex]::Escape([string]$automation.template)
      if ($workflow -notmatch "(?m)^# Template: $template\s*$") { throw "Managed workflow template does not match config" }
      if ($workflow -notmatch '(?m)^concurrency:\s*$' -or $workflow -notmatch '(?m)^\s+timeout-minutes:\s*\d+\s*$') {
        throw "Managed workflow must define concurrency and job timeouts"
      }
      foreach ($use in [regex]::Matches($workflow, '(?m)^\s*(?:-\s*)?uses:\s*(?<value>\S+)')) {
        $value = $use.Groups["value"].Value
        if ($value -notmatch '@[0-9a-f]{40}$') { throw "Managed workflow action is not pinned to a commit: $value" }
      }
      if ($workflow -match 'actions/upload-artifact@' -and $workflow -notmatch '(?m)^\s+retention-days:\s*\d+\s*$') {
        throw "Managed workflow must set artifact retention-days"
      }
    }
    if ($workflowConfig) {
      $expectedWorkflowName = [string](Get-RequiredProperty $workflowConfig "name" "publish.workflow")
      if ((Get-WorkflowName $workflow) -ne $expectedWorkflowName) { throw "Workflow name does not match publish.workflow.name" }
    }
    if ($workflow -notmatch '(?ms)^on:\s*\r?\n\s+push:\s*\r?\n\s+tags:') { throw "Workflow must use a tag push trigger" }
    if ($workflow -notmatch '(?m)^\s+contents:\s*write\s*$') { throw "Workflow must grant contents: write" }
    if ($workflow -notmatch '(?i)(releaseDraft:\s*true|gh\s+release\s+create[^\r\n]*(?:\r?\n[^\r\n]*)*?--draft)') {
      throw "Workflow must create a draft GitHub Release"
    }
    if ($configuredProjectType -eq "docker") {
      if ($workflow -notmatch '(?m)^\s+packages:\s*write\s*$') { throw "Docker workflow must grant packages: write" }
      if ($workflow -notmatch 'docker/build-push-action@(?:v7|[0-9a-f]{40})' -or $workflow -notmatch '(?m)^\s+push:\s*true\s*$') {
        throw "Docker workflow must push the generated image"
      }
    }

    $expectedAssets = @([regex]::Matches($workflow, '(?m)^# Expected asset:\s*(?<name>\S.+?)\s*$') | ForEach-Object { $_.Groups["name"].Value })
    $requiredAssets = @(Get-OptionalProperty $release "requiredAssets" @())
    if ($managed -and $expectedAssets.Count -eq 0) { throw "Managed workflow does not declare expected assets" }
    if ($managed -and $requiredAssets.Count -eq 0) { throw "Managed config does not declare required assets" }
    $compiledPatterns = @()
    foreach ($asset in $requiredAssets) {
      $pattern = [string](Get-RequiredProperty $asset "pattern" "publish.release.requiredAssets[]")
      try { $compiledPatterns += [regex]::new($pattern) } catch { throw "Invalid required asset pattern: $pattern" }
    }
    if ($expectedAssets.Count -gt 0) {
      foreach ($name in $expectedAssets) {
        if (-not @($compiledPatterns | Where-Object { $_.IsMatch($name) }).Count) { throw "Expected workflow asset is not covered by config: $name" }
      }
      foreach ($pattern in $compiledPatterns) {
        if (-not @($expectedAssets | Where-Object { $pattern.IsMatch($_) }).Count) { throw "Required asset pattern does not match a generated asset: $($pattern.ToString())" }
      }
    }
  }
  Write-Host "Valid release automation: $configFile"
}

if (-not (Test-Path -LiteralPath $RepositoryRoot -PathType Container)) { throw "Repository root not found: $RepositoryRoot" }
$script:ResolvedRepositoryRoot = Get-NormalizedPath (Resolve-Path -LiteralPath $RepositoryRoot).Path

if ($Mode -eq "Validate") {
  Invoke-Validate
}
else {
  $profile = Get-ProjectProfile $ProjectType
  if ($Mode -eq "Detect") {
    [pscustomobject][ordered]@{
      projectType = $profile.ProjectType
      projectName = $profile.ProjectName
      version = $profile.Version
      versionSource = $profile.VersionSource
      packageManager = $profile.PackageManager
      buildPath = $profile.BuildPath
    } | ConvertTo-Json -Depth 4
  }
  elseif ($Mode -eq "GenerateLocal") {
    Invoke-GenerateLocal $profile
  }
  else {
    Invoke-Generate $profile
  }
}
